### PR TITLE
yarn 1.3.2

### PR DESCRIPTION
**Pull request by pklingem**
companion PR for https://github.com/articulate/docker-articulate-node/pull/27

### CODE REVIEW

**Comment by pklingem** [comment]
@tecnobrat any objection to this?  docker-articulate-node has been running on 1.3.2 for quite a while now without issue.

**Comment by tecnobrat** [comment]
@pklingem the power is in your hands.  I would check with the content / it crews to see if they have any issues with this.

And if you're asking me, I would rather delete the node7 image completely.  Gotta find out if anyone is using it.

**Comment by fromonesrc** [comment]
Looks like only rise-pipe and esir-manage are using node:7 https://github.com/search?p=1&q=%40articulate+node%3A7+language%3ADockerfile&type=Code&utf8=%E2%9C%93

**Comment by tecnobrat** [comment]
This is ruby, so its a different tag:

https://github.com/search?utf8=%E2%9C%93&q=%40articulate+%3A2.4-node7+language%3ADockerfile&type=Code

And node8 is used here:

https://github.com/search?utf8=%E2%9C%93&q=%40articulate+%3A2.4-node8+language%3ADockerfile&type=Code

**Comment by pklingem** [comment]
so we can delete the node-7 image?

**Comment by tecnobrat** [comment]
Looks that way, yes.

**Pull request closed without merging**
